import Head from "next/head";
import { POSTS_DIR } from "../utils/constants";
import Link from "next/link";
import { getPostsInfo } from "../helpers/page_fns";
import Portfolio from "../components/portfolio/Portfolio";

export default function Home({ postsInfo }) {
  console.log(postsInfo);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Portfolio></Portfolio>

      {/* <h2 className="underline px-4">All Posts</h2>

      <div>
        {postsInfo && postsInfo.length > 0 ? (
          postsInfo.map((post) => {
            return (
              <div key={post.slug} className="mb-8">
                <h3 className="hover:text-accent hover:underline mt-2 mb-2 px-4">
                  <Link href={`posts/${encodeURIComponent(post.slug)}`}>
                    {post.title}
                  </Link>
                </h3>
                <hr className="mb-4" />
                <p className="text-left mb-2 px-4 line-clamp-2">
                  {post.description}
                </p>
              </div>
            );
          })
        ) : (
          <div className="text-center text-xl text-accent">No Posts!</div>
        )}
      </div> */}
    </>
  );
}

export async function getStaticProps(context) {
  const postsInfo = await getPostsInfo();

  return {
    props: {
      postsInfo,
    },
  };
}
